"""Added initial table

Revision ID: 4ffa380fe19b
Revises: 
Create Date: 2024-09-14 19:15:48.574133

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ffa380fe19b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bosses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('boss_day', sa.Integer(), nullable=False),
    sa.Column('boss_time', sa.String(), nullable=False),
    sa.Column('boss_names', sa.String(), nullable=False),
    sa.Column('boss_slot', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('promo_codes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('loot', sa.String(length=255), nullable=False),
    sa.Column('expire', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('owner', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('chat_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('username', sa.String(length=34), nullable=True),
    sa.Column('fullname', sa.String(length=255), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('is_subscribed', sa.Boolean(), nullable=False),
    sa.Column('is_promoted', sa.Boolean(), nullable=False),
    sa.Column('is_banned', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('push1', sa.Boolean(), nullable=False),
    sa.Column('push5', sa.Boolean(), nullable=False),
    sa.Column('push10', sa.Boolean(), nullable=False),
    sa.Column('push30', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('chat_id')
    )
    op.create_table('notification',
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('boss_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['boss_id'], ['bosses.id'], ),
    sa.ForeignKeyConstraint(['chat_id'], ['users.chat_id'], ),
    sa.PrimaryKeyConstraint('chat_id', 'boss_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notification')
    op.drop_table('users')
    op.drop_table('promo_codes')
    op.drop_table('bosses')
    # ### end Alembic commands ###
